### ISSUE TITLE
Choose TechStack & Code Style Guide

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-03#3]
Most common technologies used in Chingu projects' techstack.
Ex. Tier 1 : HTML/CSS, JavaScript
Ex.Tier 2 : HTML/CSS, JavaScript, React
Ex.Tier 3 : HTML/CSS, JavaScript, React, Express, NodeJS, MongoDB/PostgreSQL

**Comment by C0LETRA1N** [comment]
Are we confirming that we are using HTML, CSS/Bootstrap/Sass, React.js, Node.js and Firebase for the database?

**Comment by CodeMeKathy** [comment]
Based on our conversation, I recall we confirmed using HTML, CSS, Bootstrap, ReactJS, and Firebase.  With Sass and NodeJS as possibilities depending on need and time. However, NodeJS is incorporated into Firebase. I do feel the issue can be closed out.  As we have made a final decision.

**Comment by CodeMeKathy** [comment]
Confirmed TechStack & Code Style:
- HTML, CSS, Bootstrap, ReactJS, with Firebase and NodeJS, possibly Sass.
- Agreed with to use code style rules consistent with the JavaScript Standard guide using ESLint and Prettier. 
[Jest](https://jestjs.io) a JS & React Testing Framework.
